name: Go

on:
  push:
  # branches:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ['1.13', '1.14']
    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go get -v -t -d ./...
      - name: Format
        run: gofmt -d -s .
      - name: Build
        run: go build -v ./...